storybook set-upped
fossasia/pslab-desktop pull request #642
Opened 2020-10-29 11:52 UTC by Abhijay007

Add: #633 storybook environment set-upped

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix
- [x] Feature implementation
- [ ] Doc updates

* **What changes have you introduced?**
- storybook UI environment set-upped.

* **Does this PR introduce a breaking change?**
-No

* **Preview / Steps to verify your work**:

![story1](https://user-images.githubusercontent.com/64387054/97564501-b09ce700-1a0a-11eb-99e7-e0b9286662a2.JPG)

All modified and commit files.
![story5](https://user-images.githubusercontent.com/64387054/97564644-dfb35880-1a0a-11eb-95e3-ad766f465473.JPG)

storybook successfully running.
![story4](https://user-images.githubusercontent.com/64387054/97564691-f6f24600-1a0a-11eb-872d-e9b24bf03626.JPG)

2020-10-29 21:49 UTC, orangecms requested changes
Nice, thanks a lot!

Could you please tailor the Storybook setup more towards this app?
The boilerplate bits are not needed here and rather confusing. Can you instead just write 1-2 stories for existing components? :)

2020-10-30 02:12 UTC, Abhijay007 commented
> Nice, thanks a lot!
> 
> Could you please tailor the Storybook setup more towards this app?
> The boilerplate bits are not needed here and rather confusing. Can you instead just write 1-2 stories for existing components? :)

Ok sir I will try.😊

2020-10-30 02:16 UTC, Abhijay007 commented
> Nice, thanks a lot!
> 
> Could you please tailor the Storybook setup more towards this app?
> The boilerplate bits are not needed here and rather confusing. Can you instead just write 1-2 stories for existing components? :)

sir by *** boilerplate bits *** did you mean these assets and files.

![boiler](https://user-images.githubusercontent.com/64387054/97652239-f0ec7b80-1a83-11eb-956c-184cbae0c829.JPG)

2020-10-30 03:02 UTC, Abhijay007 commented
> boilerplate bits

Sir, I removed boilerplates bits from the storybook environment but can you please help me to write a story about existing components as I don't have much information about the existing components.

2020-10-30 08:17 UTC, orangecms commented on .storybook/main.js
> +    "@storybook/addon-links",
Looking all good now for the setup - could you add the `actions` addon here as well? Then it's complete. :)

I will write an example story later, need to take care of my dayjob for now :)

2020-10-30 08:22 UTC, Abhijay007 commented on .storybook/main.js
> +    "@storybook/addon-links",
ok sir I will do that 😊

2020-10-30 08:57 UTC, Abhijay007 commented on .storybook/main.js
> +    "@storybook/addon-links",
> Looking all good now for the setup - could you add the `actions` addon here as well? Then it's complete. :)
> 
> I will write an example story later, need to take care of my dayjob for now :)


***StoryBook addon actions added***

updated in dev dependencies
![action addon'](https://user-images.githubusercontent.com/64387054/97679769-b1418600-1abb-11eb-8603-8e9114e60d99.JPG)

updated in Addons
![storybook addon](https://user-images.githubusercontent.com/64387054/97679853-d2a27200-1abb-11eb-82a0-82a155b870c8.JPG)

Successful Running on StoryBook server (localhost:6000)
![actions](https://user-images.githubusercontent.com/64387054/97679989-02517a00-1abc-11eb-8588-bcc59cac274d.JPG)

2020-10-31 01:01 UTC, orangecms commented
I have picked the Storybook setup from this PR and added an example story.

Can you please rebase this branch? Then it will just have the Electron upgrade left. Please create one pull request per feature, that makes maintenance easier. Thanks a lot!

2020-10-31 02:52 UTC, Abhijay007 commented
> I have picked the Storybook setup from this PR and added an example story.
> 
> Can you please rebase this branch? Then it will just have the Electron upgrade left. Please create one pull request per feature, that makes maintenance easier. Thanks a lot!

Sir, can you please guide me to rebase this branch because I don't know how to do that.

2020-10-31 04:47 UTC, Abhijay007 commented
> I have picked the Storybook setup from this PR and added an example story.
> 
> Can you please rebase this branch? Then it will just have the Electron upgrade left. Please create one pull request per feature, that makes maintenance easier. Thanks a lot!

Sir, can you please share git commands to rebase this branch? So, I can paste that commands into Windows Powershell and get it done 😊.

2020-10-31 06:27 UTC, orangecms commented
very basic:
```
git fetch upstream
git rebase upstream/master
git push -f
```

Instead of pasting this blindly, please familiarize yourself with what it would do. There is an excellent upstream documentation: https://git-scm.com/book/en/v2/Git-Branching-Rebasing

Enjoy reading it and good luck! 🍀 :)

2020-10-31 06:41 UTC, Abhijay007 commented
> very basic:
> 
> ```
> git fetch upstream
> git rebase upstream/master
> git push -f
> ```
> 
> Instead of pasting this blindly, please familiarize yourself with what it would do. There is an excellent upstream documentation: https://git-scm.com/book/en/v2/Git-Branching-Rebasing
> 
> Enjoy reading it and good luck! 🍀 :)

Thanks a lot, Sir for this documentation I will really look forward to it 😊.

2020-10-31 06:57 UTC, Abhijay007 commented
sir, I think I made a mistake but I don't know how to revert this action.

2020-10-31 09:44 UTC, orangecms commented
I'm sorry, it's my bad actually - the base branch here is the `development` branch, actually. Could you rebase onto that please? Thank you!

2020-10-31 09:56 UTC, Abhijay007 commented
> I'm sorry, it's my bad actually - the base branch here is the `development` branch, actually. Could you rebase onto that please? Thank you!

Sir, I run these commands  but it says Everything is up-to-date
![gitbase](https://user-images.githubusercontent.com/64387054/97776358-5aa47c80-1b8d-11eb-94cf-50eb33a49616.JPG)

2020-10-31 10:22 UTC, orangecms commented
Yes, that is because `origin` your own remote. Use `upstream` instead. ;)

2020-10-31 10:39 UTC, Abhijay007 commented
> Yes, that is because `origin` is your own remote. Use `upstream` instead. ;)

Sir, I use `upstream` instead of `origin` .Then this message show up
![upstream](https://user-images.githubusercontent.com/64387054/97777060-7a3ea380-1b93-11eb-8aae-ae1b031f6763.JPG)

2020-10-31 11:36 UTC, orangecms commented
Please add the `fossasia/pslab-desktop` repository as a remote. Find the instructions either in the upstream docs on git-scm.org or in our [README](
https://github.com/fossasia/pslab-desktop#setting-up-a-development-environment).
For further feedback, please paste your console output here as text, surrounded by triple backticks. Thank you!

2020-10-31 12:07 UTC, Abhijay007 commented
> Please add the `fossasia/pslab-desktop` repository as a remote. Find the instructions either in the upstream docs on git-scm.org or in our [README](https://github.com/fossasia/pslab-desktop#setting-up-a-development-environment).
> For further feedback, please paste your console output here as text, surrounded by triple backticks. Thank you!


sir, I run the commands you said. Now it says that there are some conflicts that must be resolve to rebase the branch but I am unable to resolve conflicts because I don't have the write access. you can see conflicts down there.

```PS C:\Users\User\Desktop\PSlab\pslab-desktop> git status
On branch development
Your branch is up to date with 'origin/development'.

nothing to commit, working tree clean
PS C:\Users\User\Desktop\PSlab\pslab-desktop> git remote add upstream https://github.com/fossasia/pslab-desktop.git
fatal: remote upstream already exists.
PS C:\Users\User\Desktop\PSlab\pslab-desktop> git fetch upstream
PS C:\Users\User\Desktop\PSlab\pslab-desktop> git rebase upstream/development
error: could not apply ddda800... upgraded Concurrently
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply ddda800... upgraded Concurrently
Auto-merging public/electron.js
CONFLICT (content): Merge conflict in public/electron.js
Auto-merging package.json
CONFLICT (content): Merge conflict in package.json
PS C:\Users\User\Desktop\PSlab\pslab-desktop>```

2020-10-31 12:43 UTC, orangecms commented
You can skip those patches as suggested. There may be more.

If you run into file access issues, it is likely because of how Windows locks open files. Just close running processes that concurrently access them.

2020-10-31 12:52 UTC, Abhijay007 commented
> You can skip those patches as suggested. There may be more.
> 
> If you run into file access issues, it is likely because of how Windows locks open files. Just close running processes that concurrently access them.

Sir how can I write a commit message after it

![message](https://user-images.githubusercontent.com/64387054/97779732-05289980-1ba6-11eb-8427-5aeac49ab0ba.JPG)

2020-10-31 13:20 UTC, Abhijay007 commented
> You can skip those patches as suggested. There may be more.
> 
> If you run into file access issues, it is likely because of how Windows locks open files. Just close running processes that concurrently access them.

Sir, rebasing done but it does not get pushed and display this message.
![push](https://user-images.githubusercontent.com/64387054/97780311-ecba7e00-1ba9-11eb-8141-57f6f05f5256.JPG)

2020-10-31 13:32 UTC, orangecms commented
Detached means that it is not done yet.

Please follow the documentation I referred you to. Look for `--continue`.

2020-10-31 13:36 UTC, Abhijay007 commented
> Detached means that it is not done yet.
> 
> Please follow the documentation I referred you to. Look for `--continue`.

Sir, I use the command  `git rebase --continue` after resolving conflict. then after this
![message](https://user-images.githubusercontent.com/64387054/97780684-1a082b80-1bac-11eb-9267-e3b0e3f4fd5e.JPG)

I use the command `git push -f`

2020-10-31 13:48 UTC, orangecms commented
Please follow the documentation to write a commit message. Use any editor to do so.

2020-10-31 14:05 UTC, Abhijay007 commented
> Please follow the documentation to write a commit message. Use any editor to do so.

Sir, I already add a commit message using this process:
- First, use `i` to insert message 
- write commit message
- press `ECS` the type ` :wq`
- at the end press `enter`.

Now I need only to push this but that occur .

2020-10-31 14:22 UTC, orangecms commented
What does the documentation say about this message?

2020-10-31 14:42 UTC, Abhijay007 commented
> What does the documentation say about this message?

Sir, I think everything is done now. after running this command `git push origin HEAD:development --force`
this happened 
```
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 4 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 956 bytes | 45.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/Abhijay007/pslab-desktop
 + 800b6cd...de45108 HEAD -> development (forced update).

2020-10-31 14:49 UTC, orangecms commented on package.json
> +<<<<<<< HEAD
Those are conflict markers. You'll need to start over.

Please rebase onto development again, drop this one commit, and just run `npm` again to upgrade Electron. Then you can push again, and it will be quick. :)

2020-10-31 14:51 UTC, Abhijay007 commented on package.json
> +<<<<<<< HEAD
ok sir i will do it.

2020-10-31 15:13 UTC, Abhijay007 commented on package.json
> +<<<<<<< HEAD
> Those are conflict markers. You'll need to start over.
> 
> Please rebase onto development again, drop this one commit, and just run `npm` again to upgrade Electron. Then you can push again, and it will be quick. :)

Sir, can you please tell me how can I drop this commit.

2020-10-31 15:22 UTC, Abhijay007 commented on package.json
> +<<<<<<< HEAD
> Those are conflict markers. You'll need to start over.
> 
> Please rebase onto development again, drop this one commit, and just run `npm` again to upgrade Electron. Then you can push again, and it will be quick. :)

Sir can you please help to drop this commit while rebasing

2020-10-31 17:44 UTC, Abhijay007 commented
Sir, finally I think it's done.
I  delete that commit which causes errors and finally Updated Electron to version 10

2020-10-31 18:10 UTC, orangecms commented
Almost - please look here: https://github.com/fossasia/pslab-desktop/pull/642/commits

Now there are three patches, which resulted from conflicts. Please rebase again, drop them, and create a new patch for the Electron upgrade. Another option is to check out the `development` branch from `upstream` again, and start over from there.

2020-11-01 04:26 UTC, Abhijay007 commented
> Almost - please look here: https://github.com/fossasia/pslab-desktop/pull/642/commits
> 
> Now there are three patches, which resulted from conflicts. Please rebase again, drop them, and create a new patch for the Electron upgrade. Another option is to check out the `development` branch from `upstream` again, and start over from there.

Ok sir I will do it.

2020-11-01 04:46 UTC, Abhijay007 commented
> Almost - please look here: https://github.com/fossasia/pslab-desktop/pull/642/commits
> 
> Now there are three patches, which resulted from conflicts. Please rebase again, drop them, and create a new patch for the Electron upgrade. Another option is to check out the `development` branch from `upstream` again, and start over from there.

Sir can you please tell me how can I drop that commits.

2020-11-01 05:21 UTC, Abhijay007 commented
> > Almost - please look here: https://github.com/fossasia/pslab-desktop/pull/642/commits
> > Now there are three patches, which resulted from conflicts. Please rebase again, drop them, and create a new patch for the Electron upgrade. Another option is to check out the `development` branch from `upstream` again, and start over from there.
> 
> Ok sir I will do it.

Sir, I think it's done. I rollback those commits and Updated Electron to version 10.

2020-11-01 06:01 UTC, orangecms commented
Very good, this is now correct indeed! :)

Now there is one little challenge left: A major version upgrade implies possible breaking changes. Have you chwcked that everything still works?
Please take a look at https://github.com/fossasia/pslab-desktop/issues/646. It looks like some migration steps are  ecessary. For debugging, look at #645. Thank you!

2020-11-01 06:26 UTC, Abhijay007 commented
> Very good, this is now correct indeed! :)
> 
> Now there is one little challenge left: A major version upgrade implies possible breaking changes. Have you chwcked that everything still works?
> Please take a look at #646. It looks like some migration steps are ecessary. For debugging, look at #645. Thank you!

Ok sir I will try to do that.

2020-11-01 07:04 UTC, Abhijay007 commented
> Very good, this is now correct indeed! :)
> 
> Now there is one little challenge left: A major version upgrade implies possible breaking changes. Have you chwcked that everything still works?
> Please take a look at #646. It looks like some migration steps are ecessary. For debugging, look at #645. Thank you!

sir, can you please tell me how can I run a debug test command for electron

2020-11-01 07:34 UTC, Abhijay007 commented
> Very good, this is now correct indeed! :)
> 
> Now there is one little challenge left: A major version upgrade implies possible breaking changes. Have you chwcked that everything still works?
> Please take a look at #646. It looks like some migration steps are ecessary. For debugging, look at #645. Thank you!

Sir when I run the command `npm start` to run the project these error messages displays
```
PS C:\Users\User\Desktop\PSlab\pslab-desktop> npm start

> pslab@2.4.0 start C:\Users\User\Desktop\PSlab\pslab-desktop
> concurrently 'npm run react-start' 'wait-on http://localhost:3000/ && npm run electron-start'

[0] ''npm' is not recognized as an internal or external command,
[0] operable program or batch file.
[1] 'run' is not recognized as an internal or external command,
[1] operable program or batch file.
[2] 'react-start'' is not recognized as an internal or external command,
[2] operable program or batch file.
[3] ''wait-on' is not recognized as an internal or external command,
[3] operable program or batch file.
[4] 'http:' is not recognized as an internal or external command,
[4] operable program or batch file.
[2] react-start' exited with code 1
[1] run exited with code 1
[0] 'npm exited with code 1
[4] http://localhost:3000/ exited with code 1
[3] 'wait-on exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pslab@2.4.0 start: `concurrently 'npm run react-start' 'wait-on http://localhost:3000/ && npm run electron-start'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pslab@2.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-11-01T07_26_36_221Z-debug.log
PS C:\Users\User\Desktop\PSlab\pslab-desktop> npm run electron-start

2020-11-01 07:41 UTC, Abhijay007 commented
> > Very good, this is now correct indeed! :)
> > Now there is one little challenge left: A major version upgrade implies possible breaking changes. Have you chwcked that everything still works?
> > Please take a look at #646. It looks like some migration steps are ecessary. For debugging, look at #645. Thank you!
> 
> Sir when I run the command `npm start` to run the project these error messages displays
> 
> ```
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! pslab@2.4.0 start: `concurrently 'npm run react-start' 'wait-on http://localhost:3000/ && npm run electron-start'`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the pslab@2.4.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-11-01T07_26_36_221Z-debug.log
> ```

Can I run this command `npm cache clean --force` and re-run the `npm install` command. Or can I run this `npm run build` command instead of re-installing?

2020-11-01 11:24 UTC, orangecms commented
One way is to use the flag and env var as per #645 as mentioned above, which should also work in development, and another option is https://github.com/orangecms/pslab-desktop/commit/50ae0df676ea32c727c4122ed38f234ca5609780 which will unhide the window process in which the background tasks are run.
See also https://github.com/fossasia/pslab-desktop#ipc-and-stack

2020-11-01 12:14 UTC, Abhijay007 commented
> One way is to use the flag and env var as per #645 as mentioned above, which should also work in development, and another option is [orangecms@50ae0df](https://github.com/orangecms/pslab-desktop/commit/50ae0df676ea32c727c4122ed38f234ca5609780) which will unhide the window process in which the background tasks are run.
> See also https://github.com/fossasia/pslab-desktop#ipc-and-stack

Sir, I changed debug to true in the `public/electron.js` folder : 
 ```
 playback: '/background_tasks/playback.html',
  },
  // Set to true to unhide the window, useful for IPC debugging
  { debug: true },
);

Now, which commands should I insert in the terminal to Run Debug tests.

2020-11-01 12:16 UTC, Abhijay007 commented
> > One way is to use the flag and env var as per #645 as mentioned above, which should also work in development, and another option is [orangecms@50ae0df](https://github.com/orangecms/pslab-desktop/commit/50ae0df676ea32c727c4122ed38f234ca5609780) which will unhide the window process in which the background tasks are run.
> > See also https://github.com/fossasia/pslab-desktop#ipc-and-stack
> 
> Sir, I changed debug to true in the `public/electron.js` folder :
> 
> ```
> playback: '/background_tasks/playback.html',
>  },
>  // Set to true to unhide the window, useful for IPC debugging
>  { debug: true },
> );
> ```

Now, which commands should I insert in the terminal to Run Debug tests.

2020-11-01 13:02 UTC, orangecms commented
There are no commands. You will need to investigate the output. If it doesn't show up, you will need to figure out a way to retrieve it. This is the core intrgration piece. Read documentation from Electron and their suggestions from the links I gave you.

2020-11-01 13:15 UTC, Abhijay007 commented
> There are no commands. You will need to investigate the output. If it doesn't show up, you will need to figure out a way to retrieve it. This is the core intrgration piece. Read documentation from Electron and their suggestions from the links I gave you.

Ok sir I will try do it

2020-11-01 15:28 UTC, Abhijay007 commented
> Very good, this is now correct indeed! :)
> 
> Now there is one little challenge left: A major version upgrade implies possible breaking changes. Have you chwcked that everything still works?
> Please take a look at #646. It looks like some migration steps are ecessary. For debugging, look at #645. Thank you!

Sir this has to be true or false:
![remote](https://user-images.githubusercontent.com/64387054/97807057-a9810d80-1c84-11eb-9b8b-a88cd76f5399.JPG)

By default, it's true in the codebase so I think there is maybe no problem with this

2020-11-01 15:29 UTC, Abhijay007 commented
> > Very good, this is now correct indeed! :)
> > Now there is one little challenge left: A major version upgrade implies possible breaking changes. Have you chwcked that everything still works?
> > Please take a look at #646. It looks like some migration steps are ecessary. For debugging, look at #645. Thank you!
> 
> Sir this has to be true or false:
> ![remote](https://user-images.githubusercontent.com/64387054/97807057-a9810d80-1c84-11eb-9b8b-a88cd76f5399.JPG)
> 
> ```
>  webPreferences: {
>       nodeIntegration: true,
>       enableRemoteModule: true,
>     },
>     minWidth: 500,
>     minHeight: 300,
>   });
> ```

By default, it's true in the codebase so I think there is maybe no problem with this

2020-11-01 15:54 UTC, orangecms commented
How can you assert that it works in `linker.html`?

2020-11-01 15:57 UTC, orangecms commented
And what does the warning as reported in #646 come from?

2020-11-01 16:16 UTC, Abhijay007 commented
> And what does the warning as reported in #646 tell us / where does it come from?

> > Very good, this is now correct indeed! :)
> > Now there is one little challenge left: A major version upgrade implies possible breaking changes. Have you chwcked that everything still works?
> > Please take a look at #646. It looks like some migration steps are ecessary. For debugging, look at #645. Thank you!
> 
> Sir when I run the command `npm start` to run the project these error messages displays
> 
> ```
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! pslab@2.4.0 start: `concurrently 'npm run react-start' 'wait-on http://localhost:3000/ && npm run electron-start'`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the pslab@2.4.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-11-01T07_26_36_221Z-debug.log
> ```

Sir, I constantly get these errors and I tried many commands and solutions but it keep displaying this. I mention the commands which I use in the above comments.

Sir can you please once go through my previous comments and tell me where I made mistakes.

2020-11-01 16:17 UTC, Abhijay007 commented
> > > Very good, this is now correct indeed! :)
> > > Now there is one little challenge left: A major version upgrade implies possible breaking changes. Have you chwcked that everything still works?
> > > Please take a look at #646. It looks like some migration steps are ecessary. For debugging, look at #645. Thank you!
> > 
> > 
> > Sir when I run the command `npm start` to run the project these error messages displays
> > ```
> > npm ERR! code ELIFECYCLE
> > npm ERR! errno 1
> > npm ERR! pslab@2.4.0 start: `concurrently 'npm run react-start' 'wait-on http://localhost:3000/ && npm run electron-start'`
> > npm ERR! Exit status 1
> > npm ERR!
> > npm ERR! Failed at the pslab@2.4.0 start script.
> > npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> > 
> > npm ERR! A complete log of this run can be found in:
> > npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-11-01T07_26_36_221Z-debug.log
> > ```
> 
> Can I run this command `npm cache clean --force` and re-run the `npm install` command. Or can I run this `npm run build` command instead of re-installing?

This one

2020-11-01 16:34 UTC, orangecms commented
Ah, yes, just follow the feedback from the output. Analyze the log file.

2020-11-01 16:36 UTC, Abhijay007 commented
> Ah, yes, just follow the feedback from the output. Analyze the log file.

ok sir

2020-11-01 16:39 UTC, Abhijay007 commented
> How can you assert that it works in `linker.html`?

Sir how can I check the console output of `linker.html` by opening it with **live server** or any other method

2020-11-01 17:12 UTC, orangecms commented
> > How can you assert that it works in `linker.html`?
> 
> Sir how can I check the console output of `linker.html` by opening it with **live server** or any other method

You can do many things. The best thing to have would be integration tests, which you can use spectron for. Mind using the correct [version](https://github.com/electron-userland/spectron#version-map). Please get the Jest testing framework set up first. It might need some further configuration. You can cover this with #632 for a start and write some unit tests, e.g., for `utils/preProcessor.js`.

Here is a [*very rough* intro](https://blog.francium.tech/spectron-for-electron-apps-automation-4c2062e37beb). You will need to read a lot, try and figure things out autonomously. One hint I can give is that you need to look out for separating concerns and stubbing.

Another option is to follow the very rough steps I pointed out in the issue that I linked here and mentioned multiple times, #645. In this case, you will also need to figure things out yourself, autonomously. We have devtron among the dependencies already, though it is unmaintained and it might be that the integration is broken. Again, you would need to figure it out yourself.

I know this is very rough, and I am very sorry. You can learn a lot here about software engineering, IPC mechanisms, and especially testing and integrating systems. :) Let me know when you get stuck, maybe rather in Gitter if you prefer. ;) Good luck! 🍀

2020-11-01 17:24 UTC, Abhijay007 commented
> > > How can you assert that it works in `linker.html`?
> > 
> > 
> > Sir how can I check the console output of `linker.html` by opening it with **live server** or any other method
> 
> You can do many things. The best thing to have would be integration tests, which you can use spectron for. Mind using the correct [version](https://github.com/electron-userland/spectron#version-map). Please get the Jest testing framework set up first. It might need some further configuration. You can cover this with #632 for a start and write some unit tests, e.g., for `utils/preProcessor.js`.
> 
> Here is a [_very rough_ intro](https://blog.francium.tech/spectron-for-electron-apps-automation-4c2062e37beb). You will need to read a lot, try and figure things out autonomously. One hint I can give is that you need to look out for separating concerns and stubbing.
> 
> Another option is to follow the very rough steps I pointed out in the issue that I linked here and mentioned multiple times, #645. In this case, you will also need to figure things out yourself, autonomously. We have devtron among the dependencies already, though it is unmaintained and it might be that the integration is broken. Again, you would need to figure it out yourself.
> 
> I know this is very rough, and I am very sorry. You can learn a lot here about software engineering, IPC mechanisms, and especially testing and integrating systems. :) Let me know when you get stuck, maybe rather in Gitter if you prefer. ;) Good luck! 🍀

Ok sir I will try to figure out things. but I want to ask one thing that can I delete the folder where I clone my repo and make a new folder and reclone the repo in that because things get a little bit messy in this existing folder but I don't know whether it affects my PR or not.

2020-11-01 17:32 UTC, orangecms commented
You can always do that, yes. Your fork here on GitHub is what the PR refers to, and Git is distributed, so your local copy doesn't affect it. :)

2020-11-02 07:03 UTC, Abhijay007 commented
> You can always do that, yes. Your fork here on GitHub is what the PR refers to, and Git is distributed, so your local copy doesn't affect it. :)

Report till now:

Sir, First I install Spectron using this command `npm install --save-dev spectron`.
after that, I install Jest using this command `npm install --save-dev jest`.
Then I run `npm test` after some processing this error shows up.

`Error: Failed to start watch mode.
    at Timeout._onTimeout (C:\Users\User\node_modules\jest-haste-map\build\index.js:788:24)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)`

Then after doing some research, I install watchmen, but the same error keeps displaying

And at the end one more thing sir can you please provide me a list of tasks or the flow chart of work that I need to do because things get a little bit confusing. The last thing I know that I update electron to version 10 and rebase it, what to do after that. because I think I need to re-clone everything and need to start work again.

2020-11-02 17:19 UTC, orangecms commented
Please follow the suggestions in https://github.com/fossasia/pslab-desktop/pull/642#issuecomment-720120858 and start small. Follow the upstream documentation, read, and try things out, autonomously. There is no exact recipe. This whole procedure is all about learning. :)

2021-01-02 08:53 UTC, Abhijay007 commented
@orangecms sir I am getting this error while running react scripts on the browser. did I need to reinstall the webpack.
can you share some docs related to this error?

```

__webpack_require__
C:/notMyuserName/user/Desktop/PSlab/pslab-desktop/webpack/bootstrap:781
  778 | };
  779 | 
  780 | // Execute the module function
> 781 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  782 | 
  783 | // Flag the module as loaded
  784 | module.l = true;
View compiled
fn
C:/notMyuserName/user/Desktop/PSlab/pslab-desktop/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
Module../src/components/Appshell/index.js
C:/notMyuserName/user/Desktop/PSlab/pslab-desktop/src/components/Appshell/index.js:1
> 1 | import Appshell from './Appshell';
  2 | 
  3 | export default Appshell;
  4 | 
View compiled
__webpack_require__
C:/notMyuserName/user/Desktop/PSlab/pslab-desktop/webpack/bootstrap:781
  778 | };
  779 | 
  780 | // Execute the module function
> 781 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  782 | 
  783 | // Flag the module as loaded
  784 | module.l = true;
View compiled
fn
C:/notMyuserName/user/Desktop/PSlab/pslab-desktop/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
Module../src/App.js
http://localhost:3000/static/js/main.chunk.js:45:79
__webpack_require__
C:/notMyuserName/user/Desktop/PSlab/pslab-desktop/webpack/bootstrap:781
  778 | };
  779 | 
  780 | // Execute the module function
> 781 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  782 | 
  783 | // Flag the module as loaded
  784 | module.l = true;
View compiled
fn
C:/notMyuserName/user/Desktop/PSlab/pslab-desktop/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
Module../src/index.js
http://localhost:3000/static/js/main.chunk.js:3576:62
__webpack_require__
C:/notMyuserName/user/Desktop/PSlab/pslab-desktop/webpack/bootstrap:781
  778 | };
  779 | 
  780 | // Execute the module function
> 781 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  782 | 
  783 | // Flag the module as loaded
  784 | module.l = true;
View compiled
fn
C:/notMyuserName/user/Desktop/PSlab/pslab-desktop/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
0
http://localhost:3000/static/js/main.chunk.js:24627:18
__webpack_require__
C:/notMyuserName/user/Desktop/PSlab/pslab-desktop/webpack/bootstrap:781
  778 | };
  779 | 
  780 | // Execute the module function
> 781 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  782 | 
  783 | // Flag the module as loaded
  784 | module.l = true;
View compiled
checkDeferredModules
C:/notMyuserName/user/Desktop/PSlab/pslab-desktop/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | return result;
View compiled
Array.webpackJsonpCallback [as push]
C:/notMyuserName/user/Desktop/PSlab/pslab-desktop/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;
View compiled
(anonymous function)
http://localhost:3000/static/js/main.chunk.js:1:57
```

2021-01-02 12:36 UTC, orangecms commented
Sorry, there is no error message in there. What do you mean by "running react scripts in the browser"? We are using the `react-scripts` module from the `create-react-app` tool (https://www.npmjs.com/package/react-scripts) and the app runs in Electron.

2021-01-02 12:41 UTC, Abhijay007 commented
> Sorry, there is no error message in there. What do you mean by "running react scripts in the browser"? We are using the `react-scripts` module from the `create-react-app` tool (https://www.npmjs.com/package/react-scripts) and the app runs in Electron.

Ok, sir, I will try to resolve it

2021-03-06 09:04 UTC, Abhijay007 commented
@orangecms sir can you please close this PR for now? I will make a new PR for electron up-gradation once it done.

Sir, you can pick storybook env for now from this PR for now, or maybe you already did that. 

I will make a new PR for electron up-gradation as the setup issue in windows is resolved from this PR(#672). I will try to upgrade the version to the electron as soon as possible. 

And thanks a lot @orangecms sir for teaching me some amazing stuff related to git version control, I learned a lot from this PR, and the articles, blogs you shared helped me a lot to learn about git version control. 
looking forward to contributing more in this amazing organization.

2021-05-08 13:35 UTC, orangecms commented
Alright, closing this for now - we dug through changes for Electron nevertheless and got it up to a higher version. :) Thank you a lot!

2021-05-08 13:35 UTC, closed without merging